apiVersion: v1
data:
  default.conf: "server {\n  listen 80 default_server;\n  server_name  _;\n\n  root
    /usr/share/nginx/html;\n  index index.html index.htm;\n  \n  location / {\n    try_files
    $uri $uri/ =404;\n  }\n  \n  error_page 500 502 503 504 /50x.html;\n  \n  # CDNのキャッシュを有効にするために、Nginxに以下の設定を行う\n
    \ # 今回は/images/以下をキャッシュするようにする\n  # 参考: https://cloud.google.com/cdn/docs/caching?hl=ja\n
    \ location ~ ^/images/(.*)$ {\n    expires max;\n    add_header Cache-Control
    \"public\";\n  }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap
